### ISSUE TITLE
Create standalone CLI-based app 

### ISSUE THREAD

**Issue by Sapt-pal** [Sapt-pal/Py_Passcred#3]
***CLI*** code can be used as a back-up i.e. as a **fallback** option 

We will keep **two options** for users:
1. Basic version [Graphical]
    - Simple and easy to use
    - only basic features
2. Advanced version [CLI + GI]
    - All features unleashed
    - combination of CLI and GI as and when required

Let's develop the 2nd as CLI only for now untill GI is fully ready.

**Comment by ForsytheIshan** [comment]
i don't quite understand what you are trying to say. idk what is CLI

**Comment by Sapt-pal** [comment]
I meant the console based standalone version.(Command Line Interface)

**Comment by Sapt-pal** [comment]
CLI developement complete for now.
